### ISSUE TITLE
Upload Resume Success Message Issue

### ISSUE THREAD

**Issue by nadeeshaan** [wadsashika/Warana#45]
1. After success fully uploading all the documents the success or error message is shown. But this Message overlaps with the upload area image.
2. If it is possible please change the lime blue color in to gray like colour

**Comment by wadsashika** [comment]
I didn't get it. In upload page and process page I added all message boxes
and notifications.

On Thu, Jan 15, 2015 at 7:58 PM, Nadeeshaan Gunasinghe <
notifications@github.com> wrote:

> Assigned #45 <https://github.com/wadsashika/Warana/issues/45> to
> @wadsashika <https://github.com/wadsashika>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wadsashika/Warana/issues/45#event-219430091>.
>



-- 
W. A. Dulanga Sashika,
Undergraduate Student,
Department of Computer Science and Engineering,
University of Moratuwa.

**Comment by nadeeshaan** [comment]
Check this one on firefox
![capture](https://cloud.githubusercontent.com/assets/1329674/5759252/55829586-9cf2-11e4-8575-eaed121af627.PNG)

**Comment by wadsashika** [comment]
Ok, both firefox and chrome show success/error message like this. and how
it suppose to look?  [?] I thought this is the rit way.

On Thu, Jan 15, 2015 at 8:09 PM, Nadeeshaan Gunasinghe <
notifications@github.com> wrote:

> Check this one on firefox
> [image: capture]
> <https://cloud.githubusercontent.com/assets/1329674/5759252/55829586-9cf2-11e4-8575-eaed121af627.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wadsashika/Warana/issues/45#issuecomment-70094119>.
>



-- 
W. A. Dulanga Sashika,
Undergraduate Student,
Department of Computer Science and Engineering,
University of Moratuwa.

**Comment by nadeeshaan** [comment]
success message should appear below the lime blue area

**Comment by wadsashika** [comment]
This looks ok to me. That's why I didn't change that. Ok, I will change it.
You are the one who add this, right? Its your responsibility to fix the
issue [?]

On Thu, Jan 15, 2015 at 8:21 PM, Nadeeshaan Gunasinghe <
notifications@github.com> wrote:

> success message should appear below the lime blue area
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wadsashika/Warana/issues/45#issuecomment-70096095>.
>



-- 
W. A. Dulanga Sashika,
Undergraduate Student,
Department of Computer Science and Engineering,
University of Moratuwa.

**Comment by nadeeshaan** [comment]
Nope...
:)
Cause this looked like this due to the blue area
;)

**Comment by wadsashika** [comment]
If it wasn't you, who add this? [?]

On Thu, Jan 15, 2015 at 8:31 PM, Nadeeshaan Gunasinghe <
notifications@github.com> wrote:

> Nope...
> :)
> Cause this looked like this due to the blue area
> ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wadsashika/Warana/issues/45#issuecomment-70097756>.
>



-- 
W. A. Dulanga Sashika,
Undergraduate Student,
Department of Computer Science and Engineering,
University of Moratuwa.

**Comment by nadeeshaan** [comment]
Ane oka hadapankoooooooooooooooooooo

**Comment by wadsashika** [comment]
:) be yako mama me aca danawa.uba aca dalane inne. hari oka ain krla ant
eka damu passe

On Thu, Jan 15, 2015 at 8:34 PM, Nadeeshaan Gunasinghe <
notifications@github.com> wrote:

> Ane oka hadapankoooooooooooooooooooo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wadsashika/Warana/issues/45#issuecomment-70098381>.
>



-- 
W. A. Dulanga Sashika,
Undergraduate Student,
Department of Computer Science and Engineering,
University of Moratuwa.

**Comment by nadeeshaan** [comment]
elazz
passe hadahan
